data = [
    {'name': "Instagram", 'follower_count': 132, 'description': "Social Media Platform", 'country': "United States"},
    {'name': "Christiano Ronaldo", 'follower_count': 322, 'description': "Footballer", 'country': "Portugal"},
    {'name': "Ariana Grande", 'follower_count': 95, 'description': "Musician and actress", 'country': "United States"},
    {'name': "Dwayne Johnson", 'follower_count': 215, 'description': "Actor and professional wrestler", 'country': "United States"},
    {'name': "Vin Diesel", 'follower_count': 183, 'description': "Actor", 'country': "United States"},
    {'name': "Steve Jobs", 'follower_count': 481, 'description': "Entrepreneur", 'country': "United States"},
    {'name': "Selena Gomez", 'follower_count': 274, 'description': "Musician and actress", 'country': "United States"},
    {'name': "Kylie Jenner", 'follower_count': 198, 'description': "Reality TV star and entrepreneur", 'country': "United States"},
    {'name': "Kim Kardashian", 'follower_count': 154, 'description': "Reality TV star and entrepreneur", 'country': "United States"},
    {'name': "Lionel Messi", 'follower_count': 202, 'description': "Footballer", 'country': "Argentina"},
    {'name': "Justin Bieber", 'follower_count': 321, 'description': "Musician", 'country': "Canada"},
    {'name': "Taylor Swift", 'follower_count': 187, 'description': "Musician", 'country': "United States"},
    {'name': "Neymar Jr", 'follower_count': 158, 'description': "Footballer", 'country': "Brazil"},
    {'name': "Kendall Jenner", 'follower_count': 209, 'description': "Model and reality TV star", 'country': "United States"},
    {'name': "Jennifer Lopez", 'follower_count': 174, 'description': "Musician and actress", 'country': "United States"},
    {'name': "Nicki Minaj", 'follower_count': 213, 'description': "Musician", 'country': "United States"},
    {'name': "Miley Cyrus", 'follower_count': 108, 'description': "Musician and actress", 'country': "United States"},
    {'name': "Kourtney Kardashian", 'follower_count': 132, 'description': "Reality TV star", 'country': "United States"},
    {'name': "Kevin Hart", 'follower_count': 193, 'description': "Comedian and actor", 'country': "United States"},
    {'name': "Zendaya", 'follower_count': 172, 'description': "Actress and singer", 'country': "United States"},
    {'name': "LeBron James", 'follower_count': 283, 'description': "Basketball player", 'country': "United States"},
    {'name': "Shakira", 'follower_count': 261, 'description': "Musician", 'country': "Colombia"},
    {'name': "Cardi B", 'follower_count': 184, 'description': "Musician", 'country': "United States"},
    {'name': "Chris Hemsworth", 'follower_count': 74, 'description': "Actor", 'country': "Australia"},
    {'name': "Rihanna", 'follower_count': 265, 'description': "Musician and entrepreneur", 'country': "Barbados"},
    {'name': "Emma Watson", 'follower_count': 128, 'description': "Actress", 'country': "United Kingdom"},
    {'name': "Gal Gadot", 'follower_count': 166, 'description': "Actress", 'country': "Israel"},
    {'name': "Tom Holland", 'follower_count': 91, 'description': "Actor", 'country': "United Kingdom"},
    {'name': "Drake", 'follower_count': 231, 'description': "Musician", 'country': "Canada"},
    {'name': "Ellen DeGeneres", 'follower_count': 117, 'description': "Comedian and TV host", 'country': "United States"},
    {'name': "Shawn Mendes", 'follower_count': 188, 'description': "Musician", 'country': "Canada"},
    {'name': "Will Smith", 'follower_count': 252, 'description': "Actor and musician", 'country': "United States"},
    {'name': "Billie Eilish", 'follower_count': 148, 'description': "Musician", 'country': "United States"},
    {'name': "Zac Efron", 'follower_count': 98, 'description': "Actor", 'country': "United States"},
    {'name': "Priyanka Chopra", 'follower_count': 112, 'description': "Actress", 'country': "India"},
    {'name': "Kanye West", 'follower_count': 167, 'description': "Musician and entrepreneur", 'country': "United States"},
    {'name': "Jason Momoa", 'follower_count': 189, 'description': "Actor", 'country': "United States"},
    {'name': "Jennifer Aniston", 'follower_count': 227, 'description': "Actress", 'country': "United States"},
    {'name': "Mark Wahlberg", 'follower_count': 153, 'description': "Actor", 'country': "United States"},
    {'name': "Hugh Jackman", 'follower_count': 146, 'description': "Actor", 'country': "Australia"},
    {'name': "Chris Evans", 'follower_count': 174, 'description': "Actor", 'country': "United States"},
    {'name': "Dua Lipa", 'follower_count': 92, 'description': "Musician", 'country': "United Kingdom"},
    {'name': "Bruno Mars", 'follower_count': 123, 'description': "Musician", 'country': "United States"},
    {'name': "Katy Perry", 'follower_count': 152, 'description': "Musician", 'country': "United States"},
    {'name': "Vincent van Gogh", 'follower_count': 60, 'description': "Painter", 'country': "Netherlands"},
    {'name': "Galileo Galilei", 'follower_count': 82, 'description': "Astronomer", 'country': "Italy"},
    {'name': "Leonardo da Vinci", 'follower_count': 101, 'description': "Painter and inventor", 'country': "Italy"},
    {'name': "Albert Einstein", 'follower_count': 89, 'description': "Physicist", 'country': "Germany"},
    {'name': "Isaac Newton", 'follower_count': 132, 'description': "Physicist and mathematician", 'country': "United Kingdom"},
    {'name': "Charles Darwin", 'follower_count': 77, 'description': "Naturalist", 'country': "United Kingdom"},
    {'name': "Nikola Tesla", 'follower_count': 93, 'description': "Inventor", 'country': "Serbia"},
    {'name': "Thomas Edison", 'follower_count': 132, 'description': "Inventor", 'country': "United States"},
    {'name': "Elon Musk", 'follower_count': 145, 'description': "Entrepreneur", 'country': "United States"},
    {'name': "Jeff Bezos", 'follower_count': 215, 'description': "Entrepreneur", 'country': "United States"},
    {'name': "Oprah Winfrey", 'follower_count': 156, 'description': "TV host and entrepreneur", 'country': "United States"},
    {'name': "Stephen Hawking", 'follower_count': 110, 'description': "Physicist", 'country': "United Kingdom"},
    {'name': "Bill Gates", 'follower_count': 271, 'description': "Entrepreneur", 'country': "United States"},
    {'name': "Warren Buffett", 'follower_count': 91, 'description': "Investor", 'country': "United States"},
    {'name': "Marie Curie", 'follower_count': 79, 'description': "Physicist and chemist", 'country': "Poland"},
    {'name': "Ada Lovelace", 'follower_count': 54, 'description': "Mathematician", 'country': "United Kingdom"},
    {'name': "Alexander Graham Bell", 'follower_count': 87, 'description': "Inventor", 'country': "United Kingdom"},
    {'name': "Steve Wozniak", 'follower_count': 66, 'description': "Entrepreneur", 'country': "United States"},
    {'name': "Tim Cook", 'follower_count': 98, 'description': "CEO of Apple", 'country': "United States"},
    {'name': "Sundar Pichai", 'follower_count': 77, 'description': "CEO of Google", 'country': "United States"},
    {'name': "Satya Nadella", 'follower_count': 100, 'description': "CEO of Microsoft", 'country': "United States"},
    {'name': "Pablo Picasso", 'follower_count': 55, 'description': "Painter", 'country': "Spain"},
    {'name': "Frida Kahlo", 'follower_count': 99, 'description': "Painter", 'country': "Mexico"},
    {'name': "Sigmund Freud", 'follower_count': 76, 'description': "Psychoanalyst", 'country': "Austria"},
    {'name': "Carl Jung", 'follower_count': 89, 'description': "Psychoanalyst", 'country': "Switzerland"},
    {'name': "Friedrich Nietzsche", 'follower_count': 47, 'description': "Philosopher", 'country': "Germany"},
    {'name': "Socrates", 'follower_count': 51, 'description': "Philosopher", 'country': "Greece"},
    {'name': "Plato", 'follower_count': 59, 'description': "Philosopher", 'country': "Greece"},
    {'name': "Aristotle", 'follower_count': 72, 'description': "Philosopher", 'country': "Greece"},
    {'name': "John Lennon", 'follower_count': 137, 'description': "Musician", 'country': "United Kingdom"},
    {'name': "Paul McCartney", 'follower_count': 78, 'description': "Musician", 'country': "United Kingdom"},
    {'name': "George Harrison", 'follower_count': 65, 'description': "Musician", 'country': "United Kingdom"},
    {'name': "Ringo Starr", 'follower_count': 89, 'description': "Musician", 'country': "United Kingdom"},
    {'name': "David Bowie", 'follower_count': 92, 'description': "Musician", 'country': "United Kingdom"},
    {'name': "Elvis Presley", 'follower_count': 109, 'description': "Musician", 'country': "United States"},
    {'name': "Michael Jackson", 'follower_count': 230, 'description': "Musician", 'country': "United States"},
    {'name': "Whitney Houston", 'follower_count': 88, 'description': "Musician", 'country': "United States"},
    {'name': "Marilyn Monroe", 'follower_count': 103, 'description': "Actress", 'country': "United States"},
    {'name': "Audrey Hepburn", 'follower_count': 98, 'description': "Actress", 'country': "United Kingdom"},
    {'name': "James Dean", 'follower_count': 64, 'description': "Actor", 'country': "United States"},
    {'name': "Clark Gable", 'follower_count': 49, 'description': "Actor", 'country': "United States"},
    {'name': "Humphrey Bogart", 'follower_count': 37, 'description': "Actor", 'country': "United States"},
    {'name': "Katherine Hepburn", 'follower_count': 45, 'description': "Actress", 'country': "United States"},
    {'name': "Greta Garbo", 'follower_count': 53, 'description': "Actress", 'country': "Sweden"},
    {'name': "Ingrid Bergman", 'follower_count': 38, 'description': "Actress", 'country': "Sweden"},
    {'name': "Charlie Chaplin", 'follower_count': 59, 'description': "Actor", 'country': "United Kingdom"},
]
