[snowflake]
user = djindal@salesforce.com
authenticator = externalbrowser
account = sfdc-dp-prd
warehouse = WH_FIN_COMP_DZ
db = SSE_PRD
schema = SSE_FIN_COMP_DZ
role = SSE_FIN_COMP_WRITE

[snowflake_svc]
user = svc_bt_bu_fin_gic_python_prd
password = 2wsT8Vte5L3f7Nwod5dy2
account = sfdc-dp-prd
warehouse = WH_FIN_COMP_DZ
db = SHARED_DB_XACTLY_GIC
schema = INCENT2
#schema = SSE_FIN_COMP_DZ
role = SSE_FIN_COMP_WRITE


